SELECT DISTINCT a.RESOURCE_GROUP_ID,'',a.IP_ADDRESS,'',a.GUEST_OS,a.NAME,d.LAST_UPDATE_TIME FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c, dbo.VPX_VM_FILE_LAYOUT_EX d where a.VMID=b.ID and b.ID=c.ENTITY_ID   and a.VMID=d.VM_ID and d.LAST_UPDATE_TIME > '2015-09-11'

SELECT a.IP_ADDRESS,a.NAME,'DM',b.NAME FROM dbo.VPXV_HOSTS a,dbo.VPXV_ENTITY  b where a.FARMID=b.ID
SELECT a.IP_ADDRESS,a.NAME,'VM','T',c.NAME FROM dbo.VPXV_VMS a,dbo.VPXV_HOSTS b,dbo.VPXV_ENTITY  c where a.HOSTID=b.HOSTID and b.FARMID=c.ID 
SELECT a.IP_ADDRESS,a.NAME,'VM','T',c.NAME FROM dbo.VPXV_VMS a,dbo.VPXV_HOSTS b,dbo.VPXV_ENTITY  c where a.HOSTID=b.HOSTID and b.FARMID=c.ID  and a.POWER_STATE='Off'
SELECT a.IP_ADDRESS,a.NAME,'DM',a.POWER_STATE FROM dbo.VPXV_HOSTS a
SELECT DISTINCT a.NAME,c.NAME,a.HOSTID,a.FARMID FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in (833) and a.PRODUCT_API_VERSION >= 5.0 and a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200 and a.HOSTID in (select d.HOSTID from dbo.VPXV_VMS d where d.POWER_STATE='On' GROUP BY d.HOSTID HAVING count(d.HOSTID)<=5
SELECT DISTINCT a.NAME,c.NAME,a.HOSTID,a.FARMID FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in (833) and a.PRODUCT_API_VERSION >= 5.0 and a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200 
SELECT ID FROM dbo.VPXV_ENTITY where NAME = 'Stage2-Basic-1'
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
SELECT DISTINCT a.NAME,c.NAME,a.HOSTID,a.FARMID,a.PRODUCT_API_VERSION,b.DS_ID,b.ACCESSIBLE,b.MOUNTED,c.CAPACITY,c.FREE_SPACE,Round(convert(float,c.FREE_SPACE)/1024/1024/1024,2) FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in (50, 52, 60, 68) and a.PRODUCT_API_VERSION >= 5.0 and  a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200


SELECT a.RESOURCE_GROUP_ID,'',a.IP_ADDRESS,'',a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
SELECT NAME,PRODUCT_VERSION,PRODUCT_BUILD from dbo.VPXV_HOSTS where  PRODUCT_BUILD < '700000'
SELECT NAME,PRODUCT_VERSION,PRODUCT_BUILD from dbo.VPXV_HOSTS where PRODUCT_VERSION<'5.0.0' and PRODUCT_BUILD < '700000'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
#SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
SELECT DISTINCT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='0'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS as a,dbo.VPX_VM as b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8','10','48','50','801','1104')
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT c.IS_CONNECTED,a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
##############
##############
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='0'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b where a.VMID=b.ID and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT NAME,RESOURCE_GROUP_ID,POWER_STATE,IP_ADDRESS,VMMWARE_TOOL,TOOLS_VERSION,STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS where RESOURCE_GROUP_ID is null
#############
select name from sysobjects where type='U'
SELECT HOSTID,NAME,FARMID,ENABLED,PRODUCT_FULLNAME,PRODUCT_VERSION,PRODUCT_API_VERSION,IP_ADDRESS from dbo.VPXV_HOSTS
#######整理ip分环境，列表,注意 已连接状态
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194') 

### 查找所有环境 IP列表 ，
### 开机状态的虚拟机(不含关机和斜体字和模板机)--模板都是关机状态    斜体的会有开机状态但ip地址等信息都在
### 网卡状态是 已连接 
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
--------分环境
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1' and a.RESOURCE_GROUP_ID in ('8194')
--------- 未引进 ENTITY_ID 表之前
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b where a.VMID=b.ID and b.AGENT_ID !='0' and a.POWER_STATE='on'

#### 检测试st2的vcenter的开机状态的,vmtools状态不正常的情况，不包含dev环境,不含斜体字机  dev 是 10
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640') and  a.VMMWARE_TOOL!='ok'
---------------------检测试st3 的vcenter的vmtools状态不正常的情况
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8','10','48','50','801','1104') and  a.VMMWARE_TOOL!='ok'
--------------- 检测vmtools状态 不正常，不区分环境，
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
--------------  检测vmtools状态 不正常，不区分环境,精简
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
SELECT NAME,PRODUCT_VERSION,PRODUCT_BUILD from dbo.VPXV_HOSTS where  PRODUCT_BUILD < '700000'
SELECT NAME,PRODUCT_VERSION,PRODUCT_BUILD from dbo.VPXV_HOSTS where PRODUCT_VERSION<'5.0.0' and PRODUCT_BUILD < '700000'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
#SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
SELECT DISTINCT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='0'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS as a,dbo.VPX_VM as b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8','10','48','50','801','1104')
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT c.IS_CONNECTED,a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
##############
##############
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='0'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b where a.VMID=b.ID and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on'
SELECT NAME,RESOURCE_GROUP_ID,POWER_STATE,IP_ADDRESS,VMMWARE_TOOL,TOOLS_VERSION,STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS where RESOURCE_GROUP_ID is null
#############
select name from sysobjects where type='U'
SELECT HOSTID,NAME,FARMID,ENABLED,PRODUCT_FULLNAME,PRODUCT_VERSION,PRODUCT_API_VERSION,IP_ADDRESS from dbo.VPXV_HOSTS
#######整理ip分环境，列表,注意 已连接状态
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194') 

### 查找所有环境 IP列表 ，
### 开机状态的虚拟机(不含关机和斜体字和模板机)--模板都是关机状态    斜体的会有开机状态但ip地址等信息都在
### 网卡状态是 已连接 
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1'
--------分环境
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='1' and and a.RESOURCE_GROUP_ID in ('8194')
--------- 未引进 ENTITY_ID 表之前
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b where a.VMID=b.ID and b.AGENT_ID !='0' and a.POWER_STATE='on'

#### 检测试st2的vcenter的开机状态的,vmtools状态不正常的情况，不包含dev环境,不含斜体字机  dev 是 10
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640') and  a.VMMWARE_TOOL!='ok'
---------------------检测试st3 的vcenter的vmtools状态不正常的情况
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8','10','48','50','801','1104') and  a.VMMWARE_TOOL!='ok'
--------------- 检测vmtools状态 不正常，不区分环境，
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
--------------  检测vmtools状态 不正常，不区分环境,精简
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and  a.VMMWARE_TOOL!='ok'
SELECT a.RESOURCE_GROUP_ID,a.IP_ADDRESS,a.GUEST_OS,a.NAME,a.VMMWARE_TOOL,a.TOOLS_VERSION FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and a.RESOURCE_GROUP_ID in ('8194','8','7032','1640','10') and  a.VMMWARE_TOOL!='ok'
#### 查找模板机
SELECT NAME,RESOURCE_GROUP_ID,POWER_STATE,IP_ADDRESS,VMMWARE_TOOL,TOOLS_VERSION,STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS where RESOURCE_GROUP_ID is null
###查找非模板机 状态未知 斜体字机器  所有环境(不含st3)的找出来 vcenter 63.250所有   st3环境在另个vcenter上
SELECT a.VMID,a.NAME,a.RESOURCE_GROUP_ID,a.POWER_STATE,a.IP_ADDRESS,a.VMMWARE_TOOL,a.TOOLS_VERSION,a.STORAGE_SPACE_UPDATED_TIME FROM dbo.VPXV_VMS  a,dbo.VPX_VM  b where a.VMID=b.ID and a.IS_TEMPLATE='0' and b.AGENT_ID ='0'
##############查找开机状态，但是网卡是未连接状态的机器,注意当机器有多个网卡，有一个网卡是连接，其他是 未连接
#也会被匹配出来
SELECT a.RESOURCE_GROUP_ID,a.NAME,a.IP_ADDRESS,a.GUEST_OS FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' and a.POWER_STATE='on' and c.IS_CONNECTED='0'
######  查找2015年01.01到现在  dev环境 新克隆的虚拟机数量,注意变成一行才可用，如果多行，要放进脚本
sql_str = """
SELECT DISTINCT a.RESOURCE_GROUP_ID,'',a.IP_ADDRESS,'',a.GUEST_OS,a.NAME,d.LAST_UPDATE_TIME 
FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c, dbo.VPX_VM_FILE_LAYOUT_EX d 
where a.VMID=b.ID and b.ID=c.ENTITY_ID  and b.AGENT_ID !='0' 
and a.POWER_STATE='on' and c.IS_CONNECTED='1' and a.VMID=d.VM_ID and a.RESOURCE_GROUP_ID in ('10')
and d.LAST_UPDATE_TIME > '2015-01-01 01:05:31.943'
"""
######以上是查开机，网卡已连接机器，下面查看最近克隆的有哪些个机器,只要一个大概时间
SELECT DISTINCT a.RESOURCE_GROUP_ID,'',a.IP_ADDRESS,'',a.GUEST_OS,a.NAME,d.LAST_UPDATE_TIME FROM dbo.VPXV_VMS a,dbo.VPX_VM b, dbo.VPX_NIC c, dbo.VPX_VM_FILE_LAYOUT_EX d where a.VMID=b.ID and b.ID=c.ENTITY_ID   and a.VMID=d.VM_ID and d.LAST_UPDATE_TIME > '2015-09-07 '
##host 版本
SELECT NAME,PRODUCT_BUILD from dbo.VPXV_HOSTS
#####查找宿主机和存储对应关系

SELECT DISTINCT a.HOSTID,a.NAME,a.FARMID,a.PRODUCT_API_VERSION,b.DS_ID,b.ACCESSIBLE,b.MOUNTED,c.NAME,c.CAPACITY,c.FREE_SPACE,Round(convert(float,c.FREE_SPACE)/1024/1024/1024,2) FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in (50, 52, 60, 68) and a.PRODUCT_API_VERSION >= 5.0 and  a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200
SELECT DISTINCT a.HOSTID,a.NAME,a.FARMID,a.PRODUCT_API_VERSION,b.HOST_ID,b.DS_ID,b.ACCESSIBLE,b.MOUNTED,c.ID,c.NAME,c.CAPACITY,c.FREE_SPACE,Round(convert(float,c.FREE_SPACE)/1024/1024/1024,2) FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in ('50','52','60','68') and a.PRODUCT_API_VERSION >= 5.0 and  a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200
SELECT DISTINCT a.HOSTID,a.NAME,a.FARMID,a.PRODUCT_API_VERSION,b.HOST_ID,b.DS_ID,b.ACCESSIBLE,b.MOUNTED,c.ID,c.NAME,c.CAPACITY,c.FREE_SPACE FROM dbo.VPXV_HOSTS a,dbo.VPXV_HOST_DATASTORE b,dbo.VPXV_DATASTORE c where a.FARMID in ('50','52','60','68') and a.PRODUCT_API_VERSION >= 5.0 and  a.HOSTID=b.HOST_ID and b.DS_ID=c.ID and b.ACCESSIBLE=1 and convert(float,c.FREE_SPACE)>322122547200
##########################
